### PR TITLE
Add support for BLE temp sensors

### PR DESCRIPTION
**Pull request by mennodegraaf**
* BLE sensor address can be configured in Wifi Config, in the form `a4:c1:38:a6:73:b0` 
* Additional indoor temperature source can be configured in MQTT
* BLE sensor temperature, humidity and battery level are retrieved (only the first used)
* BLE sensor scanning during configuration can be added later

### CODE REVIEW

**Comment by mennodegraaf** [comment]
There is a bit of a weird conflict issue between `OpenTherm.h` and NimBLE, where `BLE_GATT_CHR_F_WRITE` and `BLE_GATT_CHR_F_READ` conflicts with `OpenThermMessageType::READ` and `OpenThermMessageType::WRITE`.

I fixed it by replacing all occurences of  `OpenThermMessageType::READ` with `OpenThermMessageType::READ_DATA` and `OpenThermMessageType::WRITE` with `OpenThermMessageType::WRITE_DATA`. Can you fix that in your custom OT library as well? Or find some other way?

**Comment by mennodegraaf** [comment]
It seems a PR for the OT  name clashes is already made: https://github.com/ihormelnyk/opentherm_library/pull/15

**Comment by Laxilef** [comment]
This looks great!
I'll look into this in more detail tomorrow. What sensor models is this compatible with?

**Comment by mennodegraaf** [comment]
I tested with Xiaomi Mijia sensor. But BLE has standardized UUIDs for Environmental service and Temperature/Humidity characterstics, so it is likely that other sensors also work.

**Comment by Laxilef** [comment]
Ok, thanks, I'll order a sensor for testing.

> Can you fix that in your custom OT library

You can make changes to the class and add a commit to your branch, it will automatically appear in this PR.

**Comment by Laxilef** [comment]
> With NimBLE it all just fits, but flash space is now at 96%.

Will OTA work with this partition table?
https://github.com/espressif/arduino-esp32/blob/master/tools/partitions/huge_app.csv

**Comment by mennodegraaf** [comment]
> Will OTA work with this partition table?
https://github.com/espressif/arduino-esp32/blob/master/tools/partitions/huge_app.csv

I don't think so as there is only space for 1 big application. Users can still flash it with over USB though.

**Comment by Laxilef** [comment]
Then I think we should add a constant ``USE_BLE`` for building firmware with/without bluetooth.

**Comment by mennodegraaf** [comment]
> Then I think we should add a constant USE_BLE for building firmware with/without bluetooth.

Done

**Comment by Laxilef** [comment]
Thanks!

**Pull request merged**
