### PR TITLE
Improve opentherm handling

### PR DESCRIPTION
**Pull request by mennodegraaf**
* First try setBoilerStatus, if it fails there is no need to request other info
* Do not retry to get/set non-essential parameters that the boiler does not support

### CODE REVIEW

**Comment by Laxilef** [comment]
Good idea. We could move all the methods for initialization to a new class method. And not call this method until the next reconnection. What do you think about it?

**Comment by Laxilef** [comment]
> I also wonder if the 5 times retry can be removed at all

I don't think we should do this. In some cases, such as long and/or unshielded wire, there may be interference. And then the response to the request may be TIMEOUT.

We have a ``vars.states.otStatus`` flag that can be used to call the initialization method after reconnection.

**Comment by Laxilef** [comment]
@mennodegraaf can you rewrite the code as we discussed? If there are merge conflicts, you can close the PR and open a new one.

**Comment by mennodegraaf** [comment]
I would like to, but discovered that the most recent master has in issue due to an unhandled exception in `WifiManager`
`Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.`

**Comment by mennodegraaf** [comment]
Ready to review

**Comment by Laxilef** [comment]
> I would like to, but discovered that the most recent master has in issue due to an unhandled exception in `WifiManager` `Guru Meditation Error: Core 1 panic'ed (LoadProhibited). Exception was unhandled.` At least on my D1 mini32, have you tried it on other ESP32?
> 
> Proposed fix for it in #22

Sorry, I didn't see your PR and fixed it in commit #8d92409d7b4270efcbe03f67a7b92e788f943459

**Comment by Laxilef** [comment]
Merged. Thanks!

**Pull request merged**
